reduce latency of setting a stride array to zero via broadcasting
chriselrod/StrideArrays.jl pull request #27
Opened 2021-05-11 13:56 UTC by ranocha

On `master`:
```julia
julia> using Pkg; Pkg.activate(temp=true); Pkg.add(["BenchmarkTools", "StrideArrays"]); Pkg.develop("StrideArrays")

julia> using BenchmarkTools, StrideArrays

julia> f_fill!(x) = fill!(x, zero(eltype(x)))

julia> f_broadcast!(x) = x .= zero(eltype(x))

julia> function f_loop!(x)
           @simd for i in eachindex(x)
               @inbounds x[i] = zero(eltype(x))
           end
           x
       end

julia> f_ccall!(x) = @ccall memset(pointer(x)::Ptr{Cvoid}, 0::Cint, (length(x)*sizeof(eltype(x)))::Csize_t)::Ptr{Cvoid}

julia> x_array = zeros(4, 4, 4, 250);

julia> x_stride = StrideArray(x_array);

julia> x_ptr = PtrArray(pointer(x_array), size(x_array));

julia> x_ptr_static = PtrArray(pointer(x_array), map(StaticInt, size(x_array)));

julia> for x in [x_array, x_stride, x_ptr, x_ptr_static]
           println(typeof(x))
           display(@benchmark f_fill!($x))
           display(@benchmark f_broadcast!($x))
           display(@benchmark f_loop!($x))
           display(@benchmark f_ccall!($x))
       end

Array{Float64, 4}
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.472 μs (0.00% GC)
  median time:      1.571 μs (0.00% GC)
  mean time:        1.660 μs (0.00% GC)
  maximum time:     5.080 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     10
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.458 μs (0.00% GC)
  median time:      1.506 μs (0.00% GC)
  mean time:        1.592 μs (0.00% GC)
  maximum time:     6.045 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     10
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.459 μs (0.00% GC)
  median time:      1.496 μs (0.00% GC)
  mean time:        1.565 μs (0.00% GC)
  maximum time:     5.170 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     10
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.658 μs (0.00% GC)
  median time:      1.826 μs (0.00% GC)
  mean time:        1.966 μs (0.00% GC)
  maximum time:     7.064 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     10
StrideArray{NTuple{4, Int64}, (true, true, true, true), Float64, 4, 1, 0, (1, 2, 3, 4), Tuple{StaticInt{8}, Int64, Int64, Int64}, NTuple{4, StaticInt{1}}, Array{Float64, 4}}
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.459 μs (0.00% GC)
  median time:      1.514 μs (0.00% GC)
  mean time:        1.616 μs (0.00% GC)
  maximum time:     6.029 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     10
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     3.425 μs (0.00% GC)
  median time:      3.468 μs (0.00% GC)
  mean time:        3.628 μs (0.00% GC)
  maximum time:     10.475 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     8
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.495 μs (0.00% GC)
  median time:      1.582 μs (0.00% GC)
  mean time:        1.645 μs (0.00% GC)
  maximum time:     4.689 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     10
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.586 μs (0.00% GC)
  median time:      1.749 μs (0.00% GC)
  mean time:        1.840 μs (0.00% GC)
  maximum time:     6.777 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     10
PtrArray{NTuple{4, Int64}, (true, true, true, true), Float64, 4, 1, 0, (1, 2, 3, 4), Tuple{StaticInt{8}, Int64, Int64, Int64}, NTuple{4, StaticInt{1}}}
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.511 μs (0.00% GC)
  median time:      1.585 μs (0.00% GC)
  mean time:        1.641 μs (0.00% GC)
  maximum time:     4.871 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     10
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     3.254 μs (0.00% GC)
  median time:      3.359 μs (0.00% GC)
  mean time:        3.513 μs (0.00% GC)
  maximum time:     11.556 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     8
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.521 μs (0.00% GC)
  median time:      1.617 μs (0.00% GC)
  mean time:        1.695 μs (0.00% GC)
  maximum time:     7.381 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     10
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.657 μs (0.00% GC)
  median time:      1.764 μs (0.00% GC)
  mean time:        1.870 μs (0.00% GC)
  maximum time:     6.700 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     10
PtrArray{Tuple{StaticInt{4}, StaticInt{4}, StaticInt{4}, StaticInt{250}}, (true, true, true, true), Float64, 4, 1, 0, (1, 2, 3, 4), Tuple{StaticInt{8}, StaticInt{32}, StaticInt{128}, StaticInt{512}}, NTuple{4, StaticInt{1}}}
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.496 μs (0.00% GC)
  median time:      1.574 μs (0.00% GC)
  mean time:        1.644 μs (0.00% GC)
  maximum time:     11.825 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     10
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.489 μs (0.00% GC)
  median time:      1.564 μs (0.00% GC)
  mean time:        1.623 μs (0.00% GC)
  maximum time:     4.741 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     10
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.487 μs (0.00% GC)
  median time:      1.601 μs (0.00% GC)
  mean time:        1.685 μs (0.00% GC)
  maximum time:     6.435 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     10
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.527 μs (0.00% GC)
  median time:      1.649 μs (0.00% GC)
  mean time:        1.721 μs (0.00% GC)
  maximum time:     5.719 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     10
```

In the branch of this PR:
```julia
julia> using Pkg; Pkg.activate(temp=true); Pkg.add(["BenchmarkTools", "StrideArrays"]); Pkg.develop("StrideArrays")

julia> using BenchmarkTools, StrideArrays

julia> f_fill!(x) = fill!(x, zero(eltype(x)))

julia> f_broadcast!(x) = x .= zero(eltype(x))

julia> function f_loop!(x)
           @simd for i in eachindex(x)
               @inbounds x[i] = zero(eltype(x))
           end
           x
       end

julia> f_ccall!(x) = @ccall memset(pointer(x)::Ptr{Cvoid}, 0::Cint, (length(x)*sizeof(eltype(x)))::Csize_t)::Ptr{Cvoid}

julia> x_array = zeros(4, 4, 4, 250);

julia> x_stride = StrideArray(x_array);

julia> x_ptr = PtrArray(pointer(x_array), size(x_array));

julia> x_ptr_static = PtrArray(pointer(x_array), map(StaticInt, size(x_array)));

julia> for x in [x_array, x_stride, x_ptr, x_ptr_static]
           println(typeof(x))
           display(@benchmark f_fill!($x))
           display(@benchmark f_broadcast!($x))
           display(@benchmark f_loop!($x))
           display(@benchmark f_ccall!($x))
       end

Array{Float64, 4}
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.404 μs (0.00% GC)
  median time:      1.510 μs (0.00% GC)
  mean time:        1.641 μs (0.00% GC)
  maximum time:     7.734 μs ( [...]

2021-05-11 15:07 UTC, chriselrod requested changes
Thanks for the PR!

LoopVectorization is also special casing identity/assignment like this, albeit [in a more awkward manner](https://github.com/JuliaSIMD/LoopVectorization.jl/blob/3ef16fb764901250251a48b96ce1eb43551d7408/src/broadcast.jl#L436) to still pass the `@avx` arguments used.
So it makes sense to do that here.

Mind making it a little more generic, and then also bumping the patch version so that I can make a release after merging?

2021-05-11 15:07 UTC, chriselrod commented on src/broadcast.jl
> +@inline function Base.Broadcast.materialize!(dest::AbstractStrideArray{S,D,T,N,C,B,R,X,O}, bc::Base.Broadcast.Broadcasted{ArrayStyle, Nothing, typeof(identity), Tuple{T}}) where {S,D,T,N,C,B,R,X,O,Ar
This requires `dest` and the number to be the same element type.
So if `eltype(dest) === Float64`, this will dispatch here:
```julia
dest .= 0.0;
```
but this wont:
```julia
dest .= 0;
```
Perhaps split `T` into `T1` and `T2`, and either require both to be `<: Number`, or specify `Broadcasted{DefaultArrayStyle{0}, Nothing, typeof(identity), Tuple{T})` in the signature

2021-05-11 15:52 UTC, chriselrod commented
Should be `Base.Broadcast.DefaultArrayStyle{0}`

2021-05-11 17:05 UTC, merged

2021-05-12 04:42 UTC, ranocha commented
Thanks! Looks like all tests pass on `master`, so the failure on latest Mac OS seems to be unrelated.